modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "better_smithing_ui"
version = "${version}"
displayName = "Better Smithing UI"
authors = "jj21"
description = ''''''
#logoFile = ""

[[dependencies.better_smithing_ui]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_smithing_ui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
