modLoader = "javafml"
loaderVersion = "[49,)"
issueTrackerURL = "https://github.com/jj21asd/BetterSmithingTable/issues"
license = "MIT"

[[mods]]
modId = "better_smithing_table"
version = "${version}"
displayName = "BetterSmithingTable"
authors = "jjblock21"
description = "I don't like the new smithing table menu, so I made a better one."
#logoFile = "icon.png"

[[dependencies.better_smithing_table]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_smithing_table]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.3,1.21)"
ordering = "NONE"
side = "BOTH"
