modLoader = "javafml"
loaderVersion = "[49,)"
issueTrackerURL = "https://github.com/jj21asd/BetterSmithingUI/issues"
license = "MIT"

[[mods]]
modId = "better_smithing_ui"
version = "${version}"
displayName = "Better Smithing UI"
authors = "jjblock21"
description = '''
Replaces the ugly vanilla smithing menu with an improved version
'''
logoFile = "assets/better_smithing_ui/icon.png"

[[dependencies.better_smithing_ui]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_smithing_ui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_smithing_ui]]
modId = "architectury"
mandatory = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"
