plugins {
    id 'com.gradleup.shadow'
    id 'common.process-resources'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }

    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    implementation("net.fabricmc:fabric-loader:$fabric_loader_version")

    implementation("com.terraformersmc:modmenu:$mod_menu_version")
    implementation(include("eu.midnightdust:midnightlib:${midnight_version_fabric}"))

    if (load_testing_mods.toBoolean()) {
        localRuntime("net.fabricmc.fabric-api:fabric-api:$fabric_api_version")
        localRuntime("mezz.jei:jei-${minecraft_version}-fabric:${jei_version}")
    }

    common(project(path: ':common')) { transitive = false }
    shadowBundle(project(path: ':common', configuration: 'transformProductionFabric'))
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

jar {
    dependsOn shadowJar
    from { zipTree(shadowJar.archiveFile) }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
