# gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

version = 2.2.0+1.21
maven_group = dev.jjblock21.bst
platforms = fabric,neoforge
java_version = 21

# metadata
mod_name = Better Smithing Table
mod_id = better_smithing_table
author = jjblock21
description = I dislike the smithing table menu, so I made a mod to make it look a little better.
repository_url = https://github.com/jj21asd/BetterSmithingTable
issue_tracker_url = https://github.com/jj21asd/BetterSmithingTable/issues
license = MIT

# minecraft
minecraft_version = 1.21
minecraft_version_range_fabric = >=1.21 <1.21.2
minecraft_version_range_neoforge = [1.21, 1.21.2)

fabric_loader_version = 0.19.5
fabric_loader_version_range = >=0.18.0

neoforge_version = 21.0.167
neoforge_version_range = [21.0,)
neoforge_loader_version_range = [4,)

# compile only/bundled
mod_menu_version = 11.0.5
midnight_version_fabric = 1.9.3+1.21.1-fabric
midnight_version_neoforge = 1.9.3+1.21.1-neoforge

# testing mods
load_testing_mods = true
fabric_api_version = 0.102.0+1.21
jei_version = 19.8.2.99