# gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

version = 2.2.0
maven_group = dev.jjblock21.bst
platforms = fabric,forge
java_version = 17

# metadata
mod_name = Better Smithing Table
mod_id = better_smithing_table
author = jjblock21
description = I dislike the smithing table menu, so I made a mod to make it look a little better.
repository_url = https://github.com/jj21asd/BetterSmithingTable
issue_tracker_url = https://github.com/jj21asd/BetterSmithingTable/issues
license = MIT

# minecraft
# remember to also update pack_format in pack.mcmeta
minecraft_version = 1.20.1
minecraft_version_range_fabric = >=1.20 <1.20.2
minecraft_version_range_forge = [1.20, 1.20.2)

fabric_loader_version = 0.19.5
fabric_loader_version_range = >=0.18.0

forge_version = 1.20.1-47.4.10
forge_version_range = [46.0.14,)
forge_loader_version_range = [46,)

# compile only/bundled
mod_menu_version = 7.2.2
midnight_version_fabric = 1.9.3+1.20.1-fabric
midnight_version_forge = 1.9.2+1.20.1-forge
conditional_mixin_version = 0.6.4

# testing mods
load_testing_mods = true
fabric_api_version = 0.92.12+1.20.1
jei_version = 15.59.0.211