# gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

version = 2.2.0+26.1
maven_group = dev.jjblock21.bst
platforms = fabric,neoforge
java_version = 25

# metadata
mod_name = Better Smithing Table
mod_id = better_smithing_table
author = jjblock21
description = I dislike the smithing table menu, so I made a mod to make it look a little better.
repository_url = https://github.com/jj21asd/BetterSmithingTable
issue_tracker_url = https://github.com/jj21asd/BetterSmithingTable/issues
license = MIT

# minecraft
minecraft_version = 26.1.2
minecraft_version_range_fabric = >=26.1 <=26.1.2
minecraft_version_range_neoforge = [26.1, 26.1.2]

fabric_loader_version = 0.19.5
fabric_loader_version_range = >=0.18.0

neoforge_version = 26.1.2.114
neoforge_version_range = [26.1.0,)
neoforge_loader_version_range = [4,)

# compile only/bundled
mod_menu_version = 18.0.2
midnight_version_fabric = 1.9.3+26.1-fabric
midnight_version_neoforge = 1.9.3+26.1-neoforge

# testing mods
load_testing_mods = true
fabric_api_version = 0.155.3+26.1.2
jei_version = 29.43.0.106