plugins {
    id 'common.process-resources'
}

architectury {
    common platforms.split(',')
}

dependencies {
    // make fabric loader @Environment annotations available
    implementation("net.fabricmc:fabric-loader:$fabric_loader_version")

    // make classes available at compile time
    // loader specific version is bundled in inside fabric/forge subprojects
    compileOnly("eu.midnightdust:midnightlib:$midnight_version_fabric")
    compileOnlyApi("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
}
