modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/jj21asd/BetterSmithingTable/issues"
license = "MIT"

[[mods]]
modId = "better_smithing_table"
version = "${version}"
displayName = "BetterSmithingTable"
authors = "jjblock21"
description = "I don't like the new smithing table menu, so I made a better one."
#logoFile = "icon.png"

[[dependencies.better_smithing_table]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_smithing_table]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,1.20.5)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "better_smithing_table.mixins.json"
