modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "${issue_tracker_url}"
license = "${license}"
clientSideOnly = true

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${repository_url}"
logoFile = "icon.png"
authors = "${author}"
description = '''${description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range_neoforge}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${mod_id}.mixins.json"
