modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "better_smithing_ui"
version = "${version}"
displayName = "Better Smithing UI"
authors = "jjblock21"
description = ''''''
#logoFile = ""

[[dependencies.better_smithing_ui]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_smithing_ui]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_smithing_ui]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "better_smithing_ui.mixins.json"
